import 'order_main_category_id.dart';
import 'order_product.dart';
import 'order_sub_category_id.dart';

class OrderProductList {
  static const List<OrderProduct> products = [
    // --- Beverage ---
    // 콜드 브루
    OrderProduct(
      name: '나이트로 콜드 브루',
      enName: 'Nitro Cold Brew',
      price: '6,000',
      imageUrl: 'assets/images/products/cookies_and_cream_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '돌체 콜드 브루',
      enName: 'Dolce Cold Brew',
      price: '6,000',
      imageUrl: 'assets/images/products/caffe_americano.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '콜드 브루',
      enName: 'Cold Brew',
      price: '4,900',
      imageUrl:
          'assets/images/products/caramel_brulee_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '바닐라 크림 콜드 브루',
      enName: 'Vanilla Cream Cold Brew',
      price: '5,800',
      imageUrl: 'assets/images/products/salted_caramel_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '오트 콜드 브루',
      enName: 'Oat Cold Brew',
      price: '5,800',
      imageUrl: 'assets/images/products/iced_black_tea.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '제주 비자림 콜드 브루',
      enName: 'Jeju Forest Cold Brew',
      price: '6,800',
      imageUrl: 'assets/images/products/mocha_cookie_crumble_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '시그니처 더 블랙 콜드 브루',
      enName: 'Signature The Black Cold Brew',
      price: '19,600',
      imageUrl:
          'assets/images/products/peppermint_white_chocolate_mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '콜드 브루 몰트',
      enName: 'Cold Brew Malt',
      price: '8,500',
      imageUrl: 'assets/images/products/iced_caffe_americano.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '콜드 브루 플로트',
      enName: 'Cold Brew Float',
      price: '8,000',
      imageUrl:
          'assets/images/products/peppermint_mocha_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),
    OrderProduct(
      name: '프렌치 바닐라 라떼',
      enName: 'French Vanilla Latte',
      price: '6,500',
      imageUrl: 'assets/images/products/steamed_apple_juice.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.coldBrew,
    ),

    // 에스프레소
    OrderProduct(
      name: '아메리카노',
      enName: 'Caffe Americano',
      price: '4,500',
      imageUrl:
          'assets/images/products/caramel_ribbon_crunch_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '카페 라떼',
      enName: 'Caffe Latte',
      price: '5,000',
      imageUrl: 'assets/images/products/iced_passion_tango_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '카푸치노',
      enName: 'Cappuccino',
      price: '5,000',
      imageUrl:
          'assets/images/products/espresso_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '카라멜 마키아또',
      enName: 'Caramel Macchiato',
      price: '5,900',
      imageUrl: 'assets/images/products/peppermint_mocha.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '스타벅스 돌체 라떼',
      enName: 'Starbucks Dolce Latte',
      price: '5,900',
      imageUrl: 'assets/images/products/butter_croissant.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '바닐라 빈 라떼',
      enName: 'Vanilla Bean Latte',
      price: '6,100',
      imageUrl: 'assets/images/products/chocolate_croissant.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '에스프레소',
      enName: 'Espresso',
      price: '4,000',
      imageUrl: 'assets/images/products/everything_bagel.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '에스프레소 마키아또',
      enName: 'Espresso Macchiato',
      price: '4,000',
      imageUrl:
          'assets/images/products/sugar_cookie_almondmilk_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '에스프레소 콘 파나',
      enName: 'Espresso Con Panna',
      price: '4,200',
      imageUrl: 'assets/images/products/via_sweetened_iced_coffee.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '카페 모카',
      enName: 'Caffe Mocha',
      price: '5,500',
      imageUrl: 'assets/images/products/plain_bagel.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),
    OrderProduct(
      name: '화이트 초콜릿 모카',
      enName: 'White Chocolate Mocha',
      price: '5,900',
      imageUrl:
          'assets/images/products/peppermint_mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.espresso,
    ),

    // 프라푸치노
    OrderProduct(
      name: '자바 칩 프라푸치노',
      enName: 'Java Chip Frappuccino',
      price: '6,300',
      imageUrl: 'assets/images/products/iced_peach_green_tea.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '카라멜 프라푸치노',
      enName: 'Caramel Frappuccino',
      price: '5,900',
      imageUrl: 'assets/images/products/iced_caffe_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '제주 말차 크림 프라푸치노',
      enName: 'Jeju Matcha Cream Frappuccino',
      price: '6,300',
      imageUrl: 'assets/images/products/chai_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '화이트 초콜릿 모카 프라푸치노',
      enName: 'White Chocolate Mocha Frappuccino',
      price: '6,000',
      imageUrl: 'assets/images/products/snowman_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '에스프레소 프라푸치노',
      enName: 'Espresso Frappuccino',
      price: '5,500',
      imageUrl: 'assets/images/products/starbucks_cold_brew_coffee.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '더블 에스프레소 칩 프라푸치노',
      enName: 'Double Espresso Chip Frappuccino',
      price: '6,300',
      imageUrl:
          'assets/images/products/caramel_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '초콜릿 크림 칩 프라푸치노',
      enName: 'Chocolate Cream Chip Frappuccino',
      price: '6,000',
      imageUrl: 'assets/images/products/iced_chestnut_praline_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '제주 까망 크림 프라푸치노',
      enName: 'Jeju Black Sesame Cream Frappuccino',
      price: '7,500',
      imageUrl: 'assets/images/products/iced_sugar_cookie_almondmilk_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '제주 쑥떡 크림 프라푸치노',
      enName: 'Jeju Mugwort Cream Frappuccino',
      price: '7,500',
      imageUrl: 'assets/images/products/iced_peach_green_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),
    OrderProduct(
      name: '바닐라 크림 프라푸치노',
      enName: 'Vanilla Cream Frappuccino',
      price: '5,100',
      imageUrl: 'assets/images/products/coffee_traveler___dark_roast.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.frappuccino,
    ),

    // 블렌디드
    OrderProduct(
      name: '망고 바나나 블렌디드',
      enName: 'Mango Banana Blended',
      price: '6,300',
      imageUrl: 'assets/images/products/iced_coffee_clover_vertica.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '딸기 딜라이트 요거트 블렌디드',
      enName: 'Strawberry Delight Yogurt Blended',
      price: '6,300',
      imageUrl: 'assets/images/products/espresso_macchiato.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '피치 & 레몬 블렌디드',
      enName: 'Peach & Lemon Blended',
      price: '6,300',
      imageUrl:
          'assets/images/products/chocolate_cookie_crumble_creme_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '망고 패션 티 블렌디드',
      enName: 'Mango Passion Tea Blended',
      price: '5,400',
      imageUrl: 'assets/images/products/espresso_roast.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '익스트림 티 블렌디드',
      enName: 'Xtreme Tea Blended',
      price: '6,800',
      imageUrl: 'assets/images/products/espresso_con_panna.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '여수 바다 유자 블렌디드',
      enName: 'Yeosu Sea Yuja Blended',
      price: '7,000',
      imageUrl: 'assets/images/products/ham_and_swiss_croissant.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '제주 비자림 콜드 브루',
      enName: 'Jeju Forest Cold Brew',
      price: '6,800',
      imageUrl: 'assets/images/products/iced_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '코코넛 밀크 블렌디드',
      enName: 'Coconut Milk Blended',
      price: '6,500',
      imageUrl: 'assets/images/products/petite_vanilla_bean_scone.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '오트 그린 티 블렌디드',
      enName: 'Oat Green Tea Blended',
      price: '6,500',
      imageUrl: 'assets/images/products/impossible_breakfast_sandwich.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),
    OrderProduct(
      name: '시그니처 초콜릿 블렌디드',
      enName: 'Signature Chocolate Blended',
      price: '6,500',
      imageUrl: 'assets/images/products/starbucks_blonde_espresso_roast.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.blended,
    ),

    // 티 (Tea)
    OrderProduct(
      name: '자몽 허니 블랙 티',
      enName: 'Grapefruit Honey Black Tea',
      price: '5,700',
      imageUrl:
          'assets/images/products/chestnut_praline_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '유자 민트 티',
      enName: 'Yuaja Mint Tea',
      price: '5,900',
      imageUrl:
          'assets/images/products/iced_starbucks_blonde_vanilla_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '차이 티 라떼',
      enName: 'Chai Tea Latte',
      price: '5,500',
      imageUrl: 'assets/images/products/vanilla_sweet_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '제주 유기농 말차로 만든 라떼',
      enName: 'Jeju Organic Matcha Latte',
      price: '6,100',
      imageUrl: 'assets/images/products/cinnamon_coffee_cake.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '잉글리쉬 브렉퍼스트 티',
      enName: 'English Breakfast Brewed Tea',
      price: '4,500',
      imageUrl: 'assets/images/products/caffe_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '얼 그레이 티',
      enName: 'Earl Grey Brewed Tea',
      price: '4,500',
      imageUrl: 'assets/images/products/chocolate_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '유스베리 티',
      enName: 'Youthberry Brewed Tea',
      price: '4,500',
      imageUrl: 'assets/images/products/iced_chai_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '히비스커스 블렌드 티',
      enName: 'Hibiscus Blend Brewed Tea',
      price: '4,500',
      imageUrl:
          'assets/images/products/strawberry_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '민트 블렌드 티',
      enName: 'Mint Blend Brewed Tea',
      price: '4,500',
      imageUrl: 'assets/images/products/iced_peppermint_mocha.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),
    OrderProduct(
      name: '캐모마일 블렌드 티',
      enName: 'Chamomile Blend Brewed Tea',
      price: '4,500',
      imageUrl: 'assets/images/products/coffee_traveler___pike_place_roast.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.tea,
    ),

    // 브루드 커피
    OrderProduct(
      name: '오늘의 커피',
      enName: 'Brewed Coffee',
      price: '4,200',
      imageUrl: 'assets/images/products/espresso.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '아이스 커피',
      enName: 'Iced Coffee',
      price: '4,500',
      imageUrl: 'assets/images/products/baked_apple_croissant.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '카페 베로나',
      enName: 'Caffe Verona',
      price: '5,000',
      imageUrl: 'assets/images/products/iced_caffe_mocha.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '파이크 플레이스 로스트',
      enName: 'Pike Place Roast',
      price: '5,000',
      imageUrl: 'assets/images/products/chocolate_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '디카페인 하우스 블렌드',
      enName: 'Decaf House Blend',
      price: '5,300',
      imageUrl: 'assets/images/products/caffe_mocha.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '크리스마스 블렌드',
      enName: 'Christmas Blend',
      price: '5,500',
      imageUrl: 'assets/images/products/iced_gingerbread_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '콜롬비아',
      enName: 'Colombia',
      price: '5,000',
      imageUrl:
          'assets/images/products/nondairy_salted_caramel_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '이탈리안 로스트',
      enName: 'Italian Roast',
      price: '5,000',
      imageUrl: 'assets/images/products/iced_passion_tango_tea.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '에티오피아',
      enName: 'Ethiopia',
      price: '5,500',
      imageUrl: 'assets/images/products/gingerbread_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),
    OrderProduct(
      name: '수마트라',
      enName: 'Sumatra',
      price: '5,500',
      imageUrl: 'assets/images/products/iced_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.brewedCoffee,
    ),

    // 피지오
    OrderProduct(
      name: '쿨 라임 피지오',
      enName: 'Cool Lime Fizzio',
      price: '5,900',
      imageUrl:
          'assets/images/products/iced_hazelnut_oatmilk_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '블랙 티 레모네이드 피지오',
      enName: 'Black Tea Lemonade Fizzio',
      price: '5,400',
      imageUrl: 'assets/images/products/blueberry_streusel_muffin.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '패션 탱고 티 레모네이드 피지오',
      enName: 'Passion Tango Tea Lemonade Fizzio',
      price: '5,400',
      imageUrl: 'assets/images/products/nitro_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '핑크베리 유스베리',
      enName: 'Pinkberry Youthberry',
      price: '6,100',
      imageUrl: 'assets/images/products/iced_coffee.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '오미자 셔벗 블렌디드',
      enName: 'Omija Sherbet Blended',
      price: '6,300',
      imageUrl: 'assets/images/products/mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '라임 모히또 티',
      enName: 'Lime Mojito Tea',
      price: '6,100',
      imageUrl: 'assets/images/products/iced_black_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '자몽 피지오',
      enName: 'Grapefruit Fizzio',
      price: '6,300',
      imageUrl:
          'assets/images/products/peppermint_white_chocolate_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '유자 피지오',
      enName: 'Yuja Fizzio',
      price: '6,300',
      imageUrl: 'assets/images/products/jade_citrus_mint_brewed_tea.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '레몬 에이드 피지오',
      enName: 'Lemonade Fizzio',
      price: '5,900',
      imageUrl:
          'assets/images/products/java_chip_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),
    OrderProduct(
      name: '믹스베리 피지오',
      enName: 'Mix Berry Fizzio',
      price: '6,300',
      imageUrl: 'assets/images/products/steamed_milk.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.fizzio,
    ),

    // 리프레셔
    OrderProduct(
      name: '딸기 아사이 레모네이드 스타벅스 리프레셔',
      enName: 'Strawberry Acai Lemonade Starbucks Refreshers',
      price: '5,900',
      imageUrl:
          'assets/images/products/chestnut_praline_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '망고 용과 레모네이드 스타벅스 리프레셔',
      enName: 'Mango Dragonfruit Lemonade Starbucks Refreshers',
      price: '5,900',
      imageUrl:
          'assets/images/products/iced_brown_sugar_oatmilk_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '퍼플 드링크 위드 망고 용과 스타벅스 리프레셔',
      enName: 'Purple Drink with Mango Dragonfruit Starbucks Refreshers',
      price: '5,900',
      imageUrl: 'assets/images/products/peppermint_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '핑크 드링크 위드 딸기 아사이 스타벅스 리프레셔',
      enName: 'Pink Drink with Strawberry Acai Starbucks Refreshers',
      price: '5,900',
      imageUrl: 'assets/images/products/white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '슈크림 라떼',
      enName: 'Choux Cream Latte',
      price: '6,300',
      imageUrl: 'assets/images/products/earl_grey_tea.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '바질 레몬 셔벗 블렌디드',
      enName: 'Basil Lemon Sherbet Blended',
      price: '6,500',
      imageUrl: 'assets/images/products/iced_caramel_brulee_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '코코넛 리프레셔',
      enName: 'Coconut Refreshers',
      price: '6,000',
      imageUrl: 'assets/images/products/caramel_brulee_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '라임 리프레셔',
      enName: 'Lime Refreshers',
      price: '6,000',
      imageUrl:
          'assets/images/products/sugar_cookie_almondmilk_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '베리 히비스커스 리프레셔',
      enName: 'Berry Hibiscus Refreshers',
      price: '6,000',
      imageUrl:
          'assets/images/products/caramel_brulee_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),
    OrderProduct(
      name: '쿨 라임 리프레셔',
      enName: 'Cool Lime Refreshers',
      price: '6,000',
      imageUrl: 'assets/images/products/birthday_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.refresher,
    ),

    // 미니 음료
    OrderProduct(
      name: '루비 레드 칠링 아이스 티',
      enName: 'Ruby Red Chilling Iced Tea',
      price: '8,300',
      imageUrl:
          'assets/images/products/caramel_ribbon_crunch_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '제주 유기농 말차로 만든 라떼',
      enName: 'Jeju Organic Matcha Latte',
      price: '8,300',
      imageUrl: 'assets/images/products/pistachio_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '미니 딸기 라떼',
      enName: 'Mini Strawberry Latte',
      price: '4,500',
      imageUrl: 'assets/images/products/starbucks_blonde_vanilla_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '미니 망고 스무디',
      enName: 'Mini Mango Smoothie',
      price: '4,500',
      imageUrl: 'assets/images/products/coffee_traveler___veranda_blend.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '미니 초콜릿',
      enName: 'Mini Chocolate',
      price: '4,000',
      imageUrl: 'assets/images/products/cinnamon_dolce_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '미니 바닐라 크림',
      enName: 'Mini Vanilla Cream',
      price: '4,000',
      imageUrl:
          'assets/images/products/iced_peppermint_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '미니 카라멜',
      enName: 'Mini Caramel',
      price: '4,000',
      imageUrl:
          'assets/images/products/caffe_vanilla_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '미니 헤이즐넛',
      enName: 'Mini Hazelnut',
      price: '4,000',
      imageUrl:
          'assets/images/products/coffee_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '미니 그린티',
      enName: 'Mini Green Tea',
      price: '4,500',
      imageUrl: 'assets/images/products/iced_espresso.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),
    OrderProduct(
      name: '미니 블루베리 요거트',
      enName: 'Mini Blueberry Yogurt',
      price: '4,500',
      imageUrl: 'assets/images/products/chai_creme_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.miniDrink,
    ),

    // 병음료
    OrderProduct(
      name: '한입에 쏙 고구마',
      enName: 'Sweet Potato Bite',
      price: '3,800',
      imageUrl: 'assets/images/products/iced_cinnamon_dolce_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '리얼 블루베리',
      enName: 'Real Blueberry',
      price: '3,900',
      imageUrl:
          'assets/images/products/coffee_traveler___decaf_pike_place_roast.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '딸기 가득 요거트',
      enName: 'Full of Strawberry Yogurt',
      price: '4,100',
      imageUrl: 'assets/images/products/nondairy_chocolate_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '망고 가득 요거트',
      enName: 'Full of Mango Yogurt',
      price: '4,100',
      imageUrl:
          'assets/images/products/vanilla_sweet_cream_nitro_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '블루베리 요거트',
      enName: 'Blueberry Yogurt',
      price: '3,900',
      imageUrl: 'assets/images/products/sugar_cookie_almondmilk_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '치아씨드 요거트',
      enName: 'Chia Seed Yogurt',
      price: '4,300',
      imageUrl:
          'assets/images/products/nondairy_vanilla_sweet_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '케일 & 사과 주스',
      enName: 'Kale & Apple Juice',
      price: '4,000',
      imageUrl: 'assets/images/products/london_fog_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '햇사과 주스',
      enName: 'Fresh Apple Juice',
      price: '4,000',
      imageUrl:
          'assets/images/products/cold_brew_with_nondairy_vanilla_sweet_cream_cold_foam.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '딸기 주스',
      enName: 'Strawberry Juice',
      price: '3,800',
      imageUrl: 'assets/images/products/chestnut_praline_latte.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),
    OrderProduct(
      name: '토마토 주스',
      enName: 'Tomato Juice',
      price: '3,800',
      imageUrl: 'assets/images/products/cookies_and_cream_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.bottledDrink,
    ),

    // 에이드
    OrderProduct(
      name: '라임 패션 티',
      enName: 'Lime Passion Tea',
      price: '5,600',
      imageUrl: 'assets/images/products/caffe_americano.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '자몽 셔벗 블렌디드',
      enName: 'Grapefruit Sherbet Blended',
      price: '6,300',
      imageUrl:
          'assets/images/products/caramel_brulee_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '유자 에이드',
      enName: 'Yuja Ade',
      price: '5,900',
      imageUrl: 'assets/images/products/salted_caramel_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '레몬 에이드',
      enName: 'Lemon Ade',
      price: '5,400',
      imageUrl: 'assets/images/products/iced_black_tea.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '자몽 에이드',
      enName: 'Grapefruit Ade',
      price: '5,900',
      imageUrl: 'assets/images/products/mocha_cookie_crumble_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '청포도 에이드',
      enName: 'Green Grape Ade',
      price: '6,000',
      imageUrl:
          'assets/images/products/peppermint_white_chocolate_mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '오렌지 에이드',
      enName: 'Orange Ade',
      price: '5,900',
      imageUrl: 'assets/images/products/iced_caffe_americano.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '베리 에이드',
      enName: 'Berry Ade',
      price: '6,000',
      imageUrl:
          'assets/images/products/peppermint_mocha_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '깔라만시 에이드',
      enName: 'Calamansi Ade',
      price: '6,100',
      imageUrl: 'assets/images/products/steamed_apple_juice.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),
    OrderProduct(
      name: '석류 에이드',
      enName: 'Pomegranate Ade',
      price: '6,200',
      imageUrl:
          'assets/images/products/caramel_ribbon_crunch_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.beverage,
      subCategoryId: OrderSubCategoryId.ade,
    ),

    // --- Food ---
    // 케이크
    OrderProduct(
      name: '부드러운 생크림 카스텔라',
      enName: 'Fresh Cream Castella',
      price: '4,500',
      imageUrl: 'assets/images/products/iced_passion_tango_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '클라우드 치즈 케이크',
      enName: 'Cloud Cheese Cake',
      price: '5,500',
      imageUrl:
          'assets/images/products/espresso_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '7 레이어 가나슈 케이크',
      enName: '7 Layer Ganache Cake',
      price: '5,700',
      imageUrl: 'assets/images/products/peppermint_mocha.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '레드벨벳 크림치즈 케이크',
      enName: 'Red Velvet Cream Cheese Cake',
      price: '5,500',
      imageUrl: 'assets/images/products/butter_croissant.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '마스카포네 티라미수 케이크',
      enName: 'Mascarpone Tiramisu Cake',
      price: '5,900',
      imageUrl: 'assets/images/products/chocolate_croissant.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '블루베리 쿠키 치즈 케이크',
      enName: 'Blueberry Cookie Cheese Cake',
      price: '6,900',
      imageUrl: 'assets/images/products/everything_bagel.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '슈크림 가득 바움쿠헨',
      enName: 'Choux Cream Baumkuchen',
      price: '6,900',
      imageUrl:
          'assets/images/products/sugar_cookie_almondmilk_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '더 촉촉한 초콜릿 생크림 케이크',
      enName: 'Chocolate Fresh Cream Cake',
      price: '5,900',
      imageUrl: 'assets/images/products/via_sweetened_iced_coffee.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '호두 당근 케이크',
      enName: 'Walnut Carrot Cake',
      price: '6,500',
      imageUrl: 'assets/images/products/plain_bagel.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),
    OrderProduct(
      name: '번트 치즈 케이크',
      enName: 'Burnt Cheese Cake',
      price: '6,900',
      imageUrl:
          'assets/images/products/peppermint_mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.cake,
    ),

    // 샌드위치 & 샐러드
    OrderProduct(
      name: 'B.E.L.T. 샌드위치',
      enName: 'B.E.L.T. Sandwich',
      price: '5,900',
      imageUrl: 'assets/images/products/iced_peach_green_tea.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '에그 에그 샌드위치',
      enName: 'Egg Egg Sandwich',
      price: '4,400',
      imageUrl: 'assets/images/products/iced_caffe_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '바비큐 치킨 치즈 치아바타',
      enName: 'BBQ Chicken Cheese Ciabatta',
      price: '5,800',
      imageUrl: 'assets/images/products/chai_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '햄 & 루꼴라 올리브 샌드위치',
      enName: 'Ham & Arugula Olive Sandwich',
      price: '6,200',
      imageUrl: 'assets/images/products/snowman_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '단호박 에그 샌드위치',
      enName: 'Pumpkin Egg Sandwich',
      price: '4,900',
      imageUrl: 'assets/images/products/starbucks_cold_brew_coffee.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '크랜베리 치킨 치즈 샌드위치',
      enName: 'Cranberry Chicken Cheese Sandwich',
      price: '4,500',
      imageUrl:
          'assets/images/products/caramel_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '트리플 치즈 크로크무슈',
      enName: 'Triple Cheese Croque Monsieur',
      price: '5,200',
      imageUrl: 'assets/images/products/iced_chestnut_praline_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '쉬림프 코코넛 샐러드',
      enName: 'Shrimp Coconut Salad',
      price: '6,500',
      imageUrl: 'assets/images/products/iced_sugar_cookie_almondmilk_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '로스트 치킨 샐러드',
      enName: 'Roasted Chicken Salad',
      price: '6,500',
      imageUrl: 'assets/images/products/iced_peach_green_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),
    OrderProduct(
      name: '콥 & 요거트 샐러드',
      enName: 'Cobb & Yogurt Salad',
      price: '5,800',
      imageUrl: 'assets/images/products/coffee_traveler___dark_roast.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.sandwichSalad,
    ),

    // 브레드
    OrderProduct(
      name: '하트 파이',
      enName: 'Heart Pie',
      price: '3,200',
      imageUrl: 'assets/images/products/iced_coffee_clover_vertica.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '미니 클래식 스콘',
      enName: 'Mini Classic Scone',
      price: '4,000',
      imageUrl: 'assets/images/products/espresso_macchiato.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '베이글 (플레인/블루베리)',
      enName: 'Bagel',
      price: '3,000',
      imageUrl:
          'assets/images/products/chocolate_cookie_crumble_creme_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '프렌치 크루아상',
      enName: 'French Croissant',
      price: '3,200',
      imageUrl: 'assets/images/products/espresso_roast.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '초콜릿 데니쉬 롤',
      enName: 'Chocolate Danish Roll',
      price: '3,900',
      imageUrl: 'assets/images/products/espresso_con_panna.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '연유 밀크 모닝',
      enName: 'Condensed Milk Morning',
      price: '4,300',
      imageUrl: 'assets/images/products/ham_and_swiss_croissant.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '버터 프레첼',
      enName: 'Butter Pretzel',
      price: '3,800',
      imageUrl: 'assets/images/products/iced_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '뺑 오 쇼콜라',
      enName: 'Pain au Chocolat',
      price: '3,500',
      imageUrl: 'assets/images/products/petite_vanilla_bean_scone.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '고메 버터 스콘',
      enName: 'Gourmet Butter Scone',
      price: '3,500',
      imageUrl: 'assets/images/products/impossible_breakfast_sandwich.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),
    OrderProduct(
      name: '리얼 블루베리 베이글',
      enName: 'Real Blueberry Bagel',
      price: '3,000',
      imageUrl: 'assets/images/products/starbucks_blonde_espresso_roast.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.bread,
    ),

    // 과일 & 요거트
    OrderProduct(
      name: '하루 한 컵 RED',
      enName: 'Cup of Fruit RED',
      price: '2,600',
      imageUrl:
          'assets/images/products/chestnut_praline_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '오가닉 그릭 요거트',
      enName: 'Organic Greek Yogurt',
      price: '3,900',
      imageUrl:
          'assets/images/products/iced_starbucks_blonde_vanilla_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '오가닉 그릭 요거트 플레인',
      enName: 'Organic Greek Yogurt Plain',
      price: '3,900',
      imageUrl: 'assets/images/products/vanilla_sweet_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '그래놀라 요거트',
      enName: 'Granola Yogurt',
      price: '4,200',
      imageUrl: 'assets/images/products/cinnamon_coffee_cake.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '사과 & 당근',
      enName: 'Apple & Carrot',
      price: '3,500',
      imageUrl: 'assets/images/products/caffe_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '바나나',
      enName: 'Banana',
      price: '1,500',
      imageUrl: 'assets/images/products/chocolate_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '한라봉 젤리',
      enName: 'Hallabong Jelly',
      price: '2,800',
      imageUrl: 'assets/images/products/iced_chai_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '사과 가득 핸디 젤리',
      enName: 'Apple Handy Jelly',
      price: '2,800',
      imageUrl:
          'assets/images/products/strawberry_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '딸기 가득 핸디 젤리',
      enName: 'Strawberry Handy Jelly',
      price: '2,800',
      imageUrl: 'assets/images/products/iced_peppermint_mocha.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),
    OrderProduct(
      name: '토마토 & 모짜렐라',
      enName: 'Tomato & Mozzarella',
      price: '4,500',
      imageUrl: 'assets/images/products/coffee_traveler___pike_place_roast.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.fruitYogurt,
    ),

    // 스낵 & 미니 디저트
    OrderProduct(
      name: '한입에 쏙 고구마',
      enName: 'Sweet Potato Bite',
      price: '3,800',
      imageUrl: 'assets/images/products/espresso.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '라이스 칩',
      enName: 'Rice Chip',
      price: '2,700',
      imageUrl: 'assets/images/products/baked_apple_croissant.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '더블 치즈 베이글 칩',
      enName: 'Double Cheese Bagel Chip',
      price: '2,700',
      imageUrl: 'assets/images/products/iced_caffe_mocha.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '한입에 쏙 공주 밤',
      enName: 'Chestnut Bite',
      price: '3,500',
      imageUrl: 'assets/images/products/chocolate_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '오도독 건강한 넛 & 블루베리',
      enName: 'Crunchy Nuts & Blueberry',
      price: '2,000',
      imageUrl: 'assets/images/products/caffe_mocha.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '초콜릿 월넛 브라우니',
      enName: 'Chocolate Walnut Brownie',
      price: '3,500',
      imageUrl: 'assets/images/products/iced_gingerbread_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '다크 초콜릿 카우보이 쿠키',
      enName: 'Dark Chocolate Cowboy Cookie',
      price: '2,800',
      imageUrl:
          'assets/images/products/nondairy_salted_caramel_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '화이트 초콜릿 카우보이 쿠키',
      enName: 'White Chocolate Cowboy Cookie',
      price: '2,800',
      imageUrl: 'assets/images/products/iced_passion_tango_tea.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '아몬드 토피넛 캔디',
      enName: 'Almond Toffee Nut Candy',
      price: '3,500',
      imageUrl: 'assets/images/products/gingerbread_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),
    OrderProduct(
      name: '비스코티',
      enName: 'Biscotti',
      price: '2,500',
      imageUrl: 'assets/images/products/iced_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.snackMiniDessert,
    ),

    // 아이스크림
    OrderProduct(
      name: '자바 칩 유기농 바닐라 아이스크림',
      enName: 'Java Chip Organic Vanilla Ice Cream',
      price: '2,900',
      imageUrl:
          'assets/images/products/iced_hazelnut_oatmilk_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '넛츠 초콜릿 아포가토',
      enName: 'Nuts Chocolate Affogato',
      price: '5,600',
      imageUrl: 'assets/images/products/blueberry_streusel_muffin.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '유기농 바닐라 아이스크림',
      enName: 'Organic Vanilla Ice Cream',
      price: '2,900',
      imageUrl: 'assets/images/products/nitro_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '유기농 초콜릿 아이스크림',
      enName: 'Organic Chocolate Ice Cream',
      price: '2,900',
      imageUrl: 'assets/images/products/iced_coffee.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '딸기 요거트 젤라또',
      enName: 'Strawberry Yogurt Gelato',
      price: '3,500',
      imageUrl: 'assets/images/products/mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '망고 요거트 젤라또',
      enName: 'Mango Yogurt Gelato',
      price: '3,500',
      imageUrl: 'assets/images/products/iced_black_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '바닐라 아포가토',
      enName: 'Vanilla Affogato',
      price: '5,600',
      imageUrl:
          'assets/images/products/peppermint_white_chocolate_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '초콜릿 아포가토',
      enName: 'Chocolate Affogato',
      price: '5,600',
      imageUrl: 'assets/images/products/jade_citrus_mint_brewed_tea.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '그린티 아포가토',
      enName: 'Green Tea Affogato',
      price: '6,100',
      imageUrl:
          'assets/images/products/java_chip_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),
    OrderProduct(
      name: '자바 칩 아포가토',
      enName: 'Java Chip Affogato',
      price: '6,100',
      imageUrl: 'assets/images/products/steamed_milk.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.iceCream,
    ),

    // 수프
    OrderProduct(
      name: '트러플 머쉬룸 수프',
      enName: 'Truffle Mushroom Soup',
      price: '4,200',
      imageUrl:
          'assets/images/products/chestnut_praline_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '로스트 치킨 수프',
      enName: 'Roasted Chicken Soup',
      price: '4,200',
      imageUrl:
          'assets/images/products/iced_brown_sugar_oatmilk_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '단호박 크림 수프',
      enName: 'Pumpkin Cream Soup',
      price: '4,200',
      imageUrl: 'assets/images/products/peppermint_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '토마토 로제 수프',
      enName: 'Tomato Rose Soup',
      price: '4,200',
      imageUrl: 'assets/images/products/white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '브로콜리 치즈 수프',
      enName: 'Broccoli Cheese Soup',
      price: '4,200',
      imageUrl: 'assets/images/products/earl_grey_tea.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '양송이 수프',
      enName: 'Mushroom Soup',
      price: '3,900',
      imageUrl: 'assets/images/products/iced_caramel_brulee_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '콘 크림 수프',
      enName: 'Corn Cream Soup',
      price: '3,900',
      imageUrl: 'assets/images/products/caramel_brulee_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '어니언 수프',
      enName: 'Onion Soup',
      price: '3,900',
      imageUrl:
          'assets/images/products/sugar_cookie_almondmilk_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '클램 차우더 수프',
      enName: 'Clam Chowder Soup',
      price: '4,500',
      imageUrl:
          'assets/images/products/caramel_brulee_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),
    OrderProduct(
      name: '비프 칠리 수프',
      enName: 'Beef Chili Soup',
      price: '4,500',
      imageUrl: 'assets/images/products/birthday_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.soup,
    ),

    // 브런치
    OrderProduct(
      name: '브런치 유어 웨이',
      enName: 'Brunch Your Way',
      price: '0', // 'Variable' handled as '0' or similar
      imageUrl:
          'assets/images/products/caramel_ribbon_crunch_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '베이컨 치즈 토스트',
      enName: 'Bacon Cheese Toast',
      price: '4,900',
      imageUrl: 'assets/images/products/pistachio_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '햄 & 치즈 베이글',
      enName: 'Ham & Cheese Bagel',
      price: '5,300',
      imageUrl: 'assets/images/products/starbucks_blonde_vanilla_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '에그 베이컨 파니니',
      enName: 'Egg Bacon Panini',
      price: '6,500',
      imageUrl: 'assets/images/products/coffee_traveler___veranda_blend.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '브리오슈 에그 샌드위치',
      enName: 'Brioche Egg Sandwich',
      price: '5,900',
      imageUrl: 'assets/images/products/cinnamon_dolce_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '잉글리쉬 머핀 밀 박스',
      enName: 'English Muffin Meal Box',
      price: '5,900',
      imageUrl:
          'assets/images/products/iced_peppermint_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '멕시칸 브리또 밀 박스',
      enName: 'Mexican Burrito Meal Box',
      price: '5,900',
      imageUrl:
          'assets/images/products/caffe_vanilla_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '쉬림프 로제 파스타 밀 박스',
      enName: 'Shrimp Rose Pasta Meal Box',
      price: '6,500',
      imageUrl:
          'assets/images/products/coffee_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '트러플 머쉬룸 수프',
      enName: 'Truffle Mushroom Soup',
      price: '4,200',
      imageUrl: 'assets/images/products/iced_espresso.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),
    OrderProduct(
      name: '현미 크림 수프',
      enName: 'Brown Rice Cream Soup',
      price: '3,900',
      imageUrl: 'assets/images/products/chai_creme_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.brunch,
    ),

    // 초콜릿
    OrderProduct(
      name: '시그니처 초콜릿',
      enName: 'Signature Chocolate',
      price: '5,300',
      imageUrl: 'assets/images/products/iced_cinnamon_dolce_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '화이트 초콜릿 모카',
      enName: 'White Chocolate Mocha',
      price: '5,600',
      imageUrl:
          'assets/images/products/coffee_traveler___decaf_pike_place_roast.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '아몬드 초콜릿',
      enName: 'Almond Chocolate',
      price: '3,500',
      imageUrl: 'assets/images/products/nondairy_chocolate_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '헤이즐넛 초콜릿',
      enName: 'Hazelnut Chocolate',
      price: '3,500',
      imageUrl:
          'assets/images/products/vanilla_sweet_cream_nitro_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '다크 초콜릿',
      enName: 'Dark Chocolate',
      price: '3,500',
      imageUrl: 'assets/images/products/sugar_cookie_almondmilk_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '밀크 초콜릿',
      enName: 'Milk Chocolate',
      price: '3,500',
      imageUrl:
          'assets/images/products/nondairy_vanilla_sweet_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '제주 녹차 초콜릿',
      enName: 'Jeju Green Tea Chocolate',
      price: '4,000',
      imageUrl: 'assets/images/products/london_fog_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '코인 초콜릿',
      enName: 'Coin Chocolate',
      price: '1,500',
      imageUrl:
          'assets/images/products/cold_brew_with_nondairy_vanilla_sweet_cream_cold_foam.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '초콜릿 바',
      enName: 'Chocolate Bar',
      price: '2,500',
      imageUrl: 'assets/images/products/chestnut_praline_latte.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),
    OrderProduct(
      name: '트러플 초콜릿',
      enName: 'Truffle Chocolate',
      price: '8,000',
      imageUrl: 'assets/images/products/cookies_and_cream_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.chocolate,
    ),

    // 마카롱
    OrderProduct(
      name: '블루베리 마카롱',
      enName: 'Blueberry Macaron',
      price: '2,700',
      imageUrl: 'assets/images/products/caffe_americano.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '바닐라 마카롱',
      enName: 'Vanilla Macaron',
      price: '2,700',
      imageUrl:
          'assets/images/products/caramel_brulee_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '스트로베리 마카롱',
      enName: 'Strawberry Macaron',
      price: '2,700',
      imageUrl: 'assets/images/products/salted_caramel_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '초콜릿 마카롱',
      enName: 'Chocolate Macaron',
      price: '2,700',
      imageUrl: 'assets/images/products/iced_black_tea.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '피스타치오 마카롱',
      enName: 'Pistachio Macaron',
      price: '2,700',
      imageUrl: 'assets/images/products/mocha_cookie_crumble_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '레몬 마카롱',
      enName: 'Lemon Macaron',
      price: '2,700',
      imageUrl:
          'assets/images/products/peppermint_white_chocolate_mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '얼 그레이 마카롱',
      enName: 'Earl Grey Macaron',
      price: '2,700',
      imageUrl: 'assets/images/products/iced_caffe_americano.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '솔티드 카라멜 마카롱',
      enName: 'Salted Caramel Macaron',
      price: '2,900',
      imageUrl:
          'assets/images/products/peppermint_mocha_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '라즈베리 마카롱',
      enName: 'Raspberry Macaron',
      price: '2,900',
      imageUrl: 'assets/images/products/steamed_apple_juice.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),
    OrderProduct(
      name: '흑임자 마카롱',
      enName: 'Black Sesame Macaron',
      price: '2,900',
      imageUrl:
          'assets/images/products/caramel_ribbon_crunch_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.food,
      subCategoryId: OrderSubCategoryId.macaron,
    ),

    // --- Goods ---
    // 머그 & 글라스
    OrderProduct(
      name: '그린 사이렌 클래식 머그',
      enName: 'Green Siren Classic Mug',
      price: '16,000',
      imageUrl: 'assets/images/products/iced_passion_tango_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: 'SS 블랙 데비 머그',
      enName: 'SS Black Debbie Mug',
      price: '22,000',
      imageUrl:
          'assets/images/products/espresso_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: '더블월 글라스',
      enName: 'Double Wall Glass',
      price: '18,000',
      imageUrl: 'assets/images/products/peppermint_mocha.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: '서울 투어 머그',
      enName: 'Seoul Tour Mug',
      price: '18,000',
      imageUrl: 'assets/images/products/butter_croissant.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: '제주 투어 머그',
      enName: 'Jeju Tour Mug',
      price: '18,000',
      imageUrl: 'assets/images/products/chocolate_croissant.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: '부산 투어 머그',
      enName: 'Busan Tour Mug',
      price: '18,000',
      imageUrl: 'assets/images/products/everything_bagel.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: 'SS 헤리티지 뉴턴 텀블러',
      enName: 'SS Heritage Newton Tumbler',
      price: '31,000',
      imageUrl:
          'assets/images/products/sugar_cookie_almondmilk_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: '아이코닉 사이렌 머그',
      enName: 'Iconic Siren Mug',
      price: '14,000',
      imageUrl: 'assets/images/products/via_sweetened_iced_coffee.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: '밀키 화이트 머그',
      enName: 'Milky White Mug',
      price: '15,000',
      imageUrl: 'assets/images/products/plain_bagel.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),
    OrderProduct(
      name: '스태킹 머그 세트',
      enName: 'Stacking Mug Set',
      price: '28,000',
      imageUrl:
          'assets/images/products/peppermint_mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.mugGlass,
    ),

    // 텀블러 & 보온병
    OrderProduct(
      name: 'SS 엘마 블랙 텀블러',
      enName: 'SS Elma Black Tumbler',
      price: '33,000',
      imageUrl: 'assets/images/products/iced_peach_green_tea.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: 'JNL 제트 블랙 보온병',
      enName: 'JNL Jet Black Thermos',
      price: '48,000',
      imageUrl: 'assets/images/products/iced_caffe_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: '미르 텀블러',
      enName: 'MiiR Tumbler',
      price: '35,000',
      imageUrl: 'assets/images/products/chai_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: 'SS 콩코드 텀블러',
      enName: 'SS Concorde Tumbler',
      price: '35,000',
      imageUrl: 'assets/images/products/snowman_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: 'SS 투고 텀블러',
      enName: 'SS ToGo Tumbler',
      price: '31,000',
      imageUrl: 'assets/images/products/starbucks_cold_brew_coffee.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: 'SS 오페라 텀블러',
      enName: 'SS Opera Tumbler',
      price: '33,000',
      imageUrl:
          'assets/images/products/caramel_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: 'JNM 클래식 보온병',
      enName: 'JNM Classic Thermos',
      price: '45,000',
      imageUrl: 'assets/images/products/iced_chestnut_praline_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: 'FEJ 보온병',
      enName: 'FEJ Thermos',
      price: '48,000',
      imageUrl: 'assets/images/products/iced_sugar_cookie_almondmilk_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: '스탠리 텀블러',
      enName: 'Stanley Tumbler',
      price: '37,000',
      imageUrl: 'assets/images/products/iced_peach_green_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),
    OrderProduct(
      name: '마블 화이트 보온병',
      enName: 'Marble White Thermos',
      price: '49,000',
      imageUrl: 'assets/images/products/coffee_traveler___dark_roast.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.tumblerThermos,
    ),

    // 커피 용품
    OrderProduct(
      name: '세라믹 드리퍼',
      enName: 'Ceramic Dripper',
      price: '24,000',
      imageUrl: 'assets/images/products/iced_coffee_clover_vertica.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '커피 프레스',
      enName: 'Coffee Press',
      price: '38,000',
      imageUrl: 'assets/images/products/espresso_macchiato.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '글라스 서버',
      enName: 'Glass Server',
      price: '22,000',
      imageUrl:
          'assets/images/products/chocolate_cookie_crumble_creme_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '커피 스쿱',
      enName: 'Coffee Scoop',
      price: '9,000',
      imageUrl: 'assets/images/products/espresso_roast.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '드립 케틀',
      enName: 'Drip Kettle',
      price: '42,000',
      imageUrl: 'assets/images/products/espresso_con_panna.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '핸드 그라인더',
      enName: 'Hand Grinder',
      price: '39,000',
      imageUrl: 'assets/images/products/ham_and_swiss_croissant.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '프렌치 프레스',
      enName: 'French Press',
      price: '36,000',
      imageUrl: 'assets/images/products/iced_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '사이펀',
      enName: 'Siphon',
      price: '89,000',
      imageUrl: 'assets/images/products/petite_vanilla_bean_scone.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '콜드 브루 메이커',
      enName: 'Cold Brew Maker',
      price: '25,000',
      imageUrl: 'assets/images/products/impossible_breakfast_sandwich.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),
    OrderProduct(
      name: '종이 필터',
      enName: 'Paper Filter',
      price: '3,500',
      imageUrl: 'assets/images/products/starbucks_blonde_espresso_roast.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.coffeeGoods,
    ),

    // 원두
    OrderProduct(
      name: '에스프레소 로스트 250g',
      enName: 'Espresso Roast 250g',
      price: '15,000',
      imageUrl:
          'assets/images/products/chestnut_praline_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '하우스 블렌드 250g',
      enName: 'House Blend 250g',
      price: '15,000',
      imageUrl:
          'assets/images/products/iced_starbucks_blonde_vanilla_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '파이크 플레이스 로스트 250g',
      enName: 'Pike Place Roast 250g',
      price: '15,000',
      imageUrl: 'assets/images/products/vanilla_sweet_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '카페 베로나 250g',
      enName: 'Caffe Verona 250g',
      price: '15,000',
      imageUrl: 'assets/images/products/cinnamon_coffee_cake.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '수마트라 250g',
      enName: 'Sumatra 250g',
      price: '16,000',
      imageUrl: 'assets/images/products/caffe_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '에티오피아 250g',
      enName: 'Ethiopia 250g',
      price: '18,000',
      imageUrl: 'assets/images/products/chocolate_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '콜롬비아 250g',
      enName: 'Colombia 250g',
      price: '16,000',
      imageUrl: 'assets/images/products/iced_chai_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '과테말라 안티구아 250g',
      enName: 'Guatemala Antigua 250g',
      price: '16,000',
      imageUrl:
          'assets/images/products/strawberry_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '케냐 250g',
      enName: 'Kenya 250g',
      price: '18,000',
      imageUrl: 'assets/images/products/iced_peppermint_mocha.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),
    OrderProduct(
      name: '디카페인 하우스 블렌드 250g',
      enName: 'Decaf House Blend 250g',
      price: '17,000',
      imageUrl: 'assets/images/products/coffee_traveler___pike_place_roast.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.wholeBean,
    ),

    // 비아 (VIA)
    OrderProduct(
      name: '비아 바닐라 라떼',
      enName: 'VIA Vanilla Latte',
      price: '6,900',
      imageUrl: 'assets/images/products/espresso.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 캐러멜 라떼',
      enName: 'VIA Caramel Latte',
      price: '6,900',
      imageUrl: 'assets/images/products/baked_apple_croissant.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 콜롬비아',
      enName: 'VIA Colombia',
      price: '12,800',
      imageUrl: 'assets/images/products/iced_caffe_mocha.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 하우스 블렌드',
      enName: 'VIA House Blend',
      price: '12,800',
      imageUrl: 'assets/images/products/chocolate_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 파이크 플레이스',
      enName: 'VIA Pike Place',
      price: '12,800',
      imageUrl: 'assets/images/products/caffe_mocha.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 이탈리안 로스트',
      enName: 'VIA Italian Roast',
      price: '12,800',
      imageUrl: 'assets/images/products/iced_gingerbread_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 디카페인 하우스 블렌드',
      enName: 'VIA Decaf House Blend',
      price: '13,500',
      imageUrl:
          'assets/images/products/nondairy_salted_caramel_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 모카',
      enName: 'VIA Mocha',
      price: '7,200',
      imageUrl: 'assets/images/products/iced_passion_tango_tea.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 말차',
      enName: 'VIA Matcha',
      price: '8,500',
      imageUrl: 'assets/images/products/gingerbread_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),
    OrderProduct(
      name: '비아 아이스 커피',
      enName: 'VIA Iced Coffee',
      price: '6,900',
      imageUrl: 'assets/images/products/iced_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.viaInstant,
    ),

    // 티 패키지
    OrderProduct(
      name: '제주 녹차 (15입)',
      enName: 'Jeju Green Tea',
      price: '20,000',
      imageUrl:
          'assets/images/products/iced_hazelnut_oatmilk_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '얼 그레이 (15입)',
      enName: 'Earl Grey',
      price: '20,000',
      imageUrl: 'assets/images/products/blueberry_streusel_muffin.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '잉글리쉬 브렉퍼스트 (15입)',
      enName: 'English Breakfast',
      price: '20,000',
      imageUrl: 'assets/images/products/nitro_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '차이 (15입)',
      enName: 'Chai',
      price: '20,000',
      imageUrl: 'assets/images/products/iced_coffee.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '히비스커스 (15입)',
      enName: 'Hibiscus',
      price: '20,000',
      imageUrl: 'assets/images/products/mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '민트 블렌드 (15입)',
      enName: 'Mint Blend',
      price: '20,000',
      imageUrl: 'assets/images/products/iced_black_tea_lemonade.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '유스베리 (15입)',
      enName: 'Youthberry',
      price: '22,000',
      imageUrl:
          'assets/images/products/peppermint_white_chocolate_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '캐모마일 블렌드 (15입)',
      enName: 'Chamomile Blend',
      price: '20,000',
      imageUrl: 'assets/images/products/jade_citrus_mint_brewed_tea.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '제주 유채꽃 티',
      enName: 'Jeju Canola Flower Tea',
      price: '25,000',
      imageUrl:
          'assets/images/products/java_chip_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),
    OrderProduct(
      name: '자몽 허니 블랙 티 세트',
      enName: 'Grapefruit Honey Black Tea Set',
      price: '28,000',
      imageUrl: 'assets/images/products/steamed_milk.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.teaPackage,
    ),

    // 시럽 & 소스
    OrderProduct(
      name: '바닐라 시럽 (280ml)',
      enName: 'Vanilla Syrup',
      price: '9,000',
      imageUrl:
          'assets/images/products/chestnut_praline_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '헤이즐넛 시럽 (280ml)',
      enName: 'Hazelnut Syrup',
      price: '9,000',
      imageUrl:
          'assets/images/products/iced_brown_sugar_oatmilk_shaken_espresso.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '카라멜 시럽 (280ml)',
      enName: 'Caramel Syrup',
      price: '9,000',
      imageUrl: 'assets/images/products/peppermint_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '초콜릿 소스',
      enName: 'Chocolate Sauce',
      price: '8,000',
      imageUrl: 'assets/images/products/white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '카라멜 소스',
      enName: 'Caramel Sauce',
      price: '8,000',
      imageUrl: 'assets/images/products/earl_grey_tea.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '화이트 초콜릿 소스',
      enName: 'White Chocolate Sauce',
      price: '8,500',
      imageUrl: 'assets/images/products/iced_caramel_brulee_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '클래식 시럽',
      enName: 'Classic Syrup',
      price: '8,000',
      imageUrl: 'assets/images/products/caramel_brulee_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '돌체 시럽',
      enName: 'Dolce Syrup',
      price: '9,500',
      imageUrl:
          'assets/images/products/sugar_cookie_almondmilk_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '제주 꿀',
      enName: 'Jeju Honey',
      price: '12,000',
      imageUrl:
          'assets/images/products/caramel_brulee_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),
    OrderProduct(
      name: '메이플 시럽',
      enName: 'Maple Syrup',
      price: '11,000',
      imageUrl: 'assets/images/products/birthday_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.syrupSauce,
    ),

    // 라이프스타일
    OrderProduct(
      name: '스타벅스 장우산',
      enName: 'Starbucks Umbrella',
      price: '25,000',
      imageUrl:
          'assets/images/products/caramel_ribbon_crunch_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '23 스타벅스 다이어리',
      enName: '23 Starbucks Diary',
      price: '32,000',
      imageUrl: 'assets/images/products/pistachio_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '에코백',
      enName: 'Eco Bag',
      price: '18,000',
      imageUrl: 'assets/images/products/starbucks_blonde_vanilla_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '파우치',
      enName: 'Pouch',
      price: '15,000',
      imageUrl: 'assets/images/products/coffee_traveler___veranda_blend.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '키링',
      enName: 'Key Ring',
      price: '12,000',
      imageUrl: 'assets/images/products/cinnamon_dolce_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '노트북 파우치',
      enName: 'Laptop Pouch',
      price: '35,000',
      imageUrl:
          'assets/images/products/iced_peppermint_white_chocolate_mocha.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '피크닉 매트',
      enName: 'Picnic Mat',
      price: '28,000',
      imageUrl:
          'assets/images/products/caffe_vanilla_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '쿨러백',
      enName: 'Cooler Bag',
      price: '32,000',
      imageUrl:
          'assets/images/products/coffee_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '담요',
      enName: 'Blanket',
      price: '22,000',
      imageUrl: 'assets/images/products/iced_espresso.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),
    OrderProduct(
      name: '머그 리드',
      enName: 'Mug Lid',
      price: '5,000',
      imageUrl: 'assets/images/products/chai_creme_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.lifestyle,
    ),

    // 기프트 카드
    OrderProduct(
      name: 'Thank You 카드',
      enName: 'Thank You Card',
      price: '0',
      imageUrl: 'assets/images/products/iced_cinnamon_dolce_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'Happy Birthday 카드',
      enName: 'Happy Birthday Card',
      price: '0',
      imageUrl:
          'assets/images/products/coffee_traveler___decaf_pike_place_roast.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'Congratulations 카드',
      enName: 'Congratulations Card',
      price: '0',
      imageUrl: 'assets/images/products/nondairy_chocolate_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'Love You 카드',
      enName: 'Love You Card',
      price: '0',
      imageUrl:
          'assets/images/products/vanilla_sweet_cream_nitro_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'Cheer Up 카드',
      enName: 'Cheer Up Card',
      price: '0',
      imageUrl: 'assets/images/products/sugar_cookie_almondmilk_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'Wedding 카드',
      enName: 'Wedding Card',
      price: '0',
      imageUrl:
          'assets/images/products/nondairy_vanilla_sweet_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'Graduation 카드',
      enName: 'Graduation Card',
      price: '0',
      imageUrl: 'assets/images/products/london_fog_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'New Year 카드',
      enName: 'New Year Card',
      price: '0',
      imageUrl:
          'assets/images/products/cold_brew_with_nondairy_vanilla_sweet_cream_cold_foam.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'Christmas 카드',
      enName: 'Christmas Card',
      price: '0',
      imageUrl: 'assets/images/products/chestnut_praline_latte.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),
    OrderProduct(
      name: 'Seoul City 카드',
      enName: 'Seoul City Card',
      price: '0',
      imageUrl: 'assets/images/products/cookies_and_cream_cake_pop.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.giftCard,
    ),

    // 액세서리
    OrderProduct(
      name: '베어리스타 키체인',
      enName: 'Bearista Key Chain',
      price: '14,000',
      imageUrl: 'assets/images/products/caffe_americano.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '머들러',
      enName: 'Muddler',
      price: '7,000',
      imageUrl:
          'assets/images/products/caramel_brulee_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '코스터',
      enName: 'Coaster',
      price: '5,000',
      imageUrl: 'assets/images/products/salted_caramel_cream_cold_brew.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '스트로우 세트',
      enName: 'Straw Set',
      price: '8,000',
      imageUrl: 'assets/images/products/iced_black_tea.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '보틀 커버',
      enName: 'Bottle Cover',
      price: '9,000',
      imageUrl: 'assets/images/products/mocha_cookie_crumble_frappuccino.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '텀블러 세척 솔',
      enName: 'Tumbler Brush',
      price: '6,000',
      imageUrl:
          'assets/images/products/peppermint_white_chocolate_mocha_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '커피 스쿱 클립',
      enName: 'Coffee Scoop Clip',
      price: '8,000',
      imageUrl: 'assets/images/products/iced_caffe_americano.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '티 인퓨저',
      enName: 'Tea Infuser',
      price: '15,000',
      imageUrl:
          'assets/images/products/peppermint_mocha_creme_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '드리퍼 필터 케이스',
      enName: 'Dripper Filter Case',
      price: '22,000',
      imageUrl: 'assets/images/products/steamed_apple_juice.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
    OrderProduct(
      name: '원두 보관 용기',
      enName: 'Bean Storage Container',
      price: '18,000',
      imageUrl:
          'assets/images/products/caramel_ribbon_crunch_frappuccino_blended_beverage.png',
      mainCategoryId: OrderMainCategoryId.goods,
      subCategoryId: OrderSubCategoryId.accessory,
    ),
  ];
}
